name: gravmag
channels:
  - conda-forge
dependencies:
  - python=3.7
  - basemap
  - pyshtools
  - boule
  - cartopy
  - cartopy_offlinedata
  - gmt
  - harmonica
  - ipykernel
  - matplotlib
  - netCDF4
  - numba
  - numpy
  - packaging
  - pandas
  - pip<20
  - pyproj
  - scikit-learn
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - simplekml
  - utm
  - xarray
  - pip:
    - geophpy==0.31
    - git+https://github.com/GenericMappingTools/pygmt.git@v0.3.1
