name: pheraod
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cartopy
  - dask
  - distributed
  - ipykernel
  - netcdf4
  - numpy
  - matplotlib
  - pandas
  - scipy
  - seaborn
  - xarray
  - zarr
